### ISSUE TITLE
[bug] Cannot destructure property `headless` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by kubawolanin** [TechQuery/Puppeteer-IE#4]
# Environment:

Windows 10
```
>npm -v
6.4.1
>node -v
v10.15.1
```

# Steps to reproduce:
1. Install `windows-build-tools` and `puppeteer-ie` as instructed
2. Run the following script (`ie.js` in the project folder):

```js
const puppeteer = require('puppeteer-ie');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com/');
  await page.screenshot({path: 'ie.png'});

  await browser.close();
})();
```

# Expected result:

Script runs and saves a screenshot properly.

# Actual result:

```
> node ie.js
TypeError: Cannot destructure property `headless` of 'undefined' or 'null'.
    at Function.launch (E:\webmatch\webmatch-api\node_modules\puppeteer-ie\source\index.js:53:24)
    at E:\webmatch\webmatch-api\ie.js:4:35
    at Object.<anonymous> (E:\webmatch\webmatch-api\ie.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by TomasHubelbauer** [comment]
Try explicitly passing in `{ headless: false }` (or `true`) into `launch` as an interim fix. The error log makes it sound like this fork of Puppeteer treat the options object as mandatory.

**Comment by TomasHubelbauer** [comment]
This is the related line of code:

https://github.com/TechQuery/Puppeteer-IE/blob/master/source/index.js#L53

As you can see it attempts to destructure an object with a fallback for the field value not for the object value.
